- alias: hasura
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: acridly34
  name: acridly34
- alias: new
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: clapping81
  name: clapping81
